config/routes.rb
Rails.application.routes.draw do
 
  resources :users, only: [:index]

  resources :projects do
  	resources :tasks do
  		patch :done
  	end
  	post :join
  end
  devise_for :users
  root to: "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :projects_users
  has_many :invitation, through: :projects_users, class_name: "User", foreign_key: "user_id"
  has_many :tasks
end

app/models/projects_user.rb
class ProjectsUser < ApplicationRecord
	belongs_to :invited, class_name: "Project", foreign_key: "project_id"
	belongs_to :invitation, class_name: "User", foreign_key: "user_id"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
  has_many :projects_users
  has_many :invited, through: :projects_users, class_name: "Project", foreign_key: "project_id"
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def home

	end
	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
    @projects_invited = current_user.invited
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @invite_path = "#{request.host_with_port}/projects/#{@project.id}"
    @is_invited = ProjectsUser.find_by(project_id: @project.id, user_id: current_user.id)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Projekt został stworzony.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Projekt został zaktualizowany.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Projekt został usunięty.' }
      format.json { head :no_content }
    end
  end

  def join
    @project = Project.find(params[:project_id])
    project_user = ProjectsUser.find_by(project_id: @project.id, user_id: current_user.id)

    if !project_user.blank?
      project_user.delete
      redirect_to @project, notice: 'Zostałeś usunięty z projektu.' 
    else
      project_user = ProjectsUser.new({
        project_id: @project.id,
        user_id: current_user.id
      })

      if project_user.save
        redirect_to @project, notice: 'Zostałeś dodany do projektu.' 
      else
        redirect_to @project, alert: 'Nie zostałeś dodany do projektu.' 
      end
    end

   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:new, :create, :edit, :update, :destroy, :done]
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :project_users, only: [:new, :edit]

  # GET /projects/1/tasks/1
  # GET /projects/1/tasks/1.json
  def show
  end

  # GET /projects/1/tasks/new
  def new
    @task = Task.new
  end

  # GET /projects/1/tasks/1/edit
  def edit
  end

  # POST /projects/1/tasks
  # POST /projects/1/tasks.json
  def create
    @task = Task.new(task_params)
    @task.project = @project

    respond_to do |format|
      if @task.save
        format.html { redirect_to @project, notice: 'Zadanie zostało stworzone.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1/tasks/1
  # PATCH/PUT /projects/1/tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @project, notice: 'Zadanie zostało zaktualizowane.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1/tasks/1
  # DELETE /projects/1/tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to @project, notice: 'Zadanie zostało usunięte.' }
      format.json { head :no_content }
    end
  end

  def done
    @task = Task.find(params[:task_id])

    if @task.update(done: !@task.done)
      redirect_to @project, notice: 'Zadanie zostało zaktualizowane.'
    else
      redirect_to @project, alert: 'Zadanie nie zostało zaktualizowane.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :user_id, :done)
    end

    def project_users
      @project_users = @project.invitation.to_a
      @project_users.push(@project.user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # Return all users. Only for admin.
  def index
  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

	def join_button
		if @project.user != current_user
			if !@is_invited
				link_to "Dołącz", project_join_path(@project), class: "btn btn-success btn-join", method: :post
			else
				link_to "Opuść", project_join_path(@project), class: "btn btn-danger btn-join", method: :post
			end	 
		end
	end
end

app/helpers/tasks_helper.rb
module TasksHelper

	def done_button(task)
		if task.done
			link_to "Powrót do zadania", project_task_done_path(task.project, task), class: "btn btn-warning", method: :patch
		else
			link_to "Zakończ zadanie", project_task_done_path(task.project, task), class: "btn btn-success", method: :patch
		end	 
	end

	def done_label(task)
		if task.done
			content_tag(:span, "Zakończone", class: "label label-success")
		else
			content_tag(:span, "W toku", class: "label label-warning")		
		end	 
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Homepage</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'partials/navbar' %>
  	<%= render 'partials/alerts' %>
    <div class="container-fluid main-container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/partials/_alerts.html.erb
<%- if alert %>
	<div class="alert alert-danger alert-dismissible" role="alert">
  		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  		<%= alert %>
	</div>
<%- end %>

<%- if notice %>
	<div class="alert alert-success alert-dismissible" role="alert">
  		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  		<%= notice %>
	</div>
<%- end %>

app/views/partials/_empty_data.html.erb
<div class="jumbotron text-center">
  Brak rekordów
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Projekt manager", root_path, class: "navbar-brand"%>
    </div>

	  <ul class="nav navbar-nav">
	    <li><%= link_to "Projekty", root_path%></li>
	    <% if user_signed_in? && current_user.admin %>
	   	 	<li><%= link_to "Użytkownicy", users_path %></li>
	    <% end %>
	  </ul>	
	  <ul class="nav navbar-nav navbar-right">
	    <%- if user_signed_in? %>
	    	<li><%= link_to "Wyloguj", destroy_user_session_path, method: "delete" %></li>
	    <% else %>
	    	<li><%= link_to "Rejestracja", new_user_registration_path %></li>
	   		<li><%= link_to "Zaloguj", new_user_session_path %></li>
	    <% end %>
	  </ul>
  </div>
</nav>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Nazwa" %>
    <%= form.text_field :name, id: :project_name, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nazwa projektu</th>
      <th>Użytkownik</th>
      <th>Przypisani</th>
      <th>Zadania</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.user.email %></td>
        <td><%= project.invitation.count %></td>
        <td><%= project.tasks.count %></td>
        <td>
          <%= link_to 'Szczegóły', project, class: "btn btn-primary" %>
          <%- if project.user == current_user %>
          	<%= link_to 'Edycja', edit_project_path(project), class: "btn btn-primary" %>
          	<%= link_to 'Usuń', project, class: "btn btn-primary", method: :delete, data: { confirm: 'Czy jesteś pewien?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if projects.blank? %>
  <%= render 'partials/empty_data' %>
<% end %>

app/views/projects/edit.html.erb
<div class="container form">
	<h1>Edycja projektu</h1>

	<%= render 'form', project: @project, button: "Edytuj" %>
	<hr>
	<%= link_to 'Szczegóły', @project, class: "btn btn-primary" %> |
	<%= link_to 'Powrót', projects_path, class: "btn btn-primary" %>
</div>

app/views/projects/index.html.erb
<h1>Projekty</h1>
<hr>
<div class="row">
	<div class="col-md-6">
		<h2>Moje projekty</h2>
	</div>
	<div class="col-md-6 text-right">
		<%= link_to 'Dodaj nowy projekt', new_project_path, class: "btn btn-primary" %>
	</div>
</div>


<%= render 'index', projects: @projects %>

<h2>Przypisane</h2>
<%= render 'index', projects: @projects_invited %>

<br>

app/views/projects/new.html.erb
<div class="container form">
	<h1>Nowy projekt</h1>

	<%= render 'form', project: @project, button: "Dodaj" %>
	<hr>
	<%= link_to 'Powrót', projects_path, class: "btn btn-primary" %>
</div>

app/views/projects/show.html.erb
<h1>Szczegóły projektu</h1>
<hr>
<%= join_button %>
<dl class="dl-horizontal">
  <dt>Nazwa projektu:</dt>
  <dd><%= @project.name %></dd>

  <dt>Właściciel projektu:</dt>
  <dd><%= @project.user.email %></dd>

  <dt>Zaproś:</dt>
  <dd><%= text_field_tag :invite_path, @invite_path %></dd>
</dl>

<%= render 'tasks/index', tasks: @project.tasks %>
<hr>
<% if @project.user == current_user %>
	<%= link_to 'Edycja', edit_project_path(@project), class: "btn btn-primary" %> |
<% end %>
<%= link_to 'Powrót', projects_path, class: "btn btn-primary" %>

app/views/tasks/_form.html.erb
<%= form_for([@project, @task]) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this @task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Nazwa" %>
    <%= form.text_field :name, id: :task_name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Zadanie dla:" %>
    <%= form.collection_select :user_id, @project_users, :id, :email, {}, {class:"form-control"} %>
  </div>

  <div class="checkbox">
    <label>
      <%= form.check_box :done, id: :task_done %> 
      <%= form.label "Zakończone" %>
    </label>
  </div>

  <div class="actions text-right">
    <%= form.submit button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/_index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Zadania</h1>
  </div>
  <div class="col-md-6 text-right">
    <% if @is_invited || @project.user == current_user %>
      <%= link_to 'Nowe zadanie', new_project_task_path(@project), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nazwa zadania</th>
      <th>Użytkownik</th>
      <th>Status zadania</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.user.email %></td>
        <td><%= done_label(task) %></td>
        
        <td>
          <% if @project.user == current_user || task.user == current_user %>
            <%= done_button(task) %>
            <%= link_to 'Edytuj', edit_project_task_path(@project, task), class: "btn btn-primary" %>
            <%= link_to 'Usuń', [@project,task], method: :delete, class: "btn btn-primary", data: { confirm: 'Czy jesteś pewien?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if tasks.blank? %>
  <%= render 'partials/empty_data' %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container form">
	<h1>Edycja zadania</h1>

	<%= render 'form', button: "Zaktualizuj" %>
	<hr>
	<%= link_to 'Powrót', @project, class: "btn btn-primary" %>
</div>

app/views/tasks/new.html.erb
<div class="container form">
	<h1>Nowe zadanie</h1>

	<%= render 'form', button: "Dodaj" %>
	<hr>
	<%= link_to 'Powrót', @project, class: "btn btn-primary" %>
</div>

app/views/users/index.html.erb
<h1>Użytkownicy</h1>
<hr>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Email</th>
      <th>Projekty</th>
      <th>Przypisany do</th>
      <th>Zadania</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.projects.count %></td>
        <td><%= user.invited.count %></td>
        <td><%= user.tasks.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>